name: NS8 Release on PR Merge to Main

on:
  pull_request:
    types: [closed]
    paths-ignore:
      - '.github/**'
      - 'tests/**'
      - 'README.md'
      - '.gitignore'
      - 'LICENSE'
      - 'renovate.json'
      - 'test-module.sh'

env:
  GH_TOKEN: ${{ secrets.NS8_MODULE_RELEASES_TOKEN }}

jobs:
  release-module:
    if: >
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Install NS8 Release Module Extension
        run: gh extension install NethServer/gh-ns8-release-module

      - name: Create Testing Release
        run: gh ns8-release-module create --repo ${{ github.repository }} --testing
